<a href="https://colab.research.google.com/github/Hyphen-14/Scientific-Computing/blob/Session1/SC_sesi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sesi 1 --> Modul ada di Section 2

# New Section

In [ ]:
print ("Hello world\n")

Hello world



In [ ]:
import time
print(time.ctime())

Thu Feb  6 04:41:40 2025


In [ ]:
z = "Hello"
y = 20
c = 30.7
f = ["Apple", "berry"]

z, y, c, f
print(z, y, c, f)

Hello 20 30.7 ['Apple', 'berry']


In [ ]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)

print (o, y, z, j)

1 2 3 20


In [ ]:
a = "Hello"
b = " World"
c = a+b
print(c)

Hello World


In [ ]:
from re import A
a = "Hello World"
print(a[1])

print(len(a))

e
11


In [ ]:
b = "Binus University"
print(b[2:5])

c = "Binus University"
print(c[:5])

d = "Binus University"
print(d[2:])



nus
Binus
nus University


In [ ]:
a = "Hello"
print(a.upper())
print(a.lower())
print(a.replace("H", "3"))

HELLO
hello
3ello


In [ ]:
nama = "Yasin"
x = 19
string = "Nama saya {} umur {}"
print (string.format(nama, x))

Nama saya Yasin umur 19


In [ ]:
nama = "Ahmad"
for i in enumerate(nama):
  print(i)

(0, 'A')
(1, 'h')
(2, 'm')
(3, 'a')
(4, 'd')


In [ ]:
def perbandingan (a, b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a = b")

In [ ]:
perbandingan(3214, 3843)

a kurang dari b


In [ ]:
i=1
while i<6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
i=1
for i in range(0,6):
  print(i)

0
1
2
3
4
5


In [ ]:

for i in range (2, 41):
  if i%2 == 0:
    print(str(i) + " genap")
  else:
    print(str(i) + " ganjil")

2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil
20 genap
21 ganjil
22 genap
23 ganjil
24 genap
25 ganjil
26 genap
27 ganjil
28 genap
29 ganjil
30 genap
31 ganjil
32 genap
33 ganjil
34 genap
35 ganjil
36 genap
37 ganjil
38 genap
39 ganjil
40 genap


In [ ]:
import numpy as np

Membuat matrix menggunakan np

In [ ]:
x = np.array([[1, 2, 3], [3, 6, 7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8, 2, 9], [3, 5, 7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

Penjumlahan Matrix

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array ([10, 9, 8, 7, 5, 6,])

print("Rata-rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))
print("Standar Devisiasi:", np.std(data))

Rata-rata: 7.5
Maksimum: 10
Minimum: 5
Standar Devisiasi: 1.707825127659933


# New Section

Modul Sesi 1

Login

In [25]:

username = input("Masukkan username : ")

password = input("Masukkan password : ")
while password != "Admin123":
  password = input("Password anda salah, coba lagi : ")
print("Login Berhasil, Selamat datang " + username)

Masukkan username : Yasin
Masukkan password : Admin123
Login Berhasil, Selamat datang Yasin


Input data mahasiswa

In [33]:
nama = input("Masukkan nama mahasiswa : ")

while True:
    uts = float(input("Masukkan nilai UTS : "))
    if 0 <= uts <= 100:
        break  # Keluar dari loop jika input valid
    print("Invalid input [0-100], coba lagi.")


while True:
    uas = float(input("Masukkan nilai UAS : "))
    if 0 <= uas <= 100:
        break
    print("Invalid input [0-100], coba lagi.")


while True:
    asg = float(input("Masukkan nilai Assignment : "))
    if 0 <= asg <= 100:
        break
    print("Invalid input [0-100], coba lagi.")


Masukkan nama mahasiswa : Umar
Masukkan nilai UTS : 78
Masukkan nilai UAS : 86
Masukkan nilai Assignment : 90


Final Score function

In [41]:
def calculate(uts, uas, asg):
  return (uas * 0.5) + (uts * 0.3) + (asg * 0.2)

score = calculate(uts, uas, asg)
print(score)

84.4


Grading Function

In [47]:
def grading(score):
  if 100 >= score >= 90:
    return "Grade A"
  elif 89.99 >= score >= 85:
    return "Grade A-"
  elif 84.99 >= score >= 80:
    return "Grade B+"
  elif 79.99 >= score >= 75:
    return "Grade B"
  elif 74.99 >= score >= 70:
    return "Grade B-"
  elif 69.99 >= score >= 65:
    return "Grade C+"
  elif 64.99 >= score >= 60:
    return "Grade C"
  elif 59.99 >= score >= 11:
    return "Grade C-"
  else :
    return "Grade F"



Print Hasil perolehan nilai

In [49]:
print("=============================")
print("Hasil perolehan nilai " + nama)
print("Final Score: " + str(calculate(uts, uas, asg)))
print(grading(score))

Hasil perolehan nilai Umar
Final Score: 84.4
Grade B+
